name: Rust

on:
  workflow_dispatch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: funkdigen2-mac
        path: target/release/funkdigen2
  
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: funkdigen2-windows
        path: target/release/funkdigen2.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: funkdigen2-ubuntu
        path: target/release/funkdigen2
